/*Created by:
cat resources/Kommunnamn-URL.csv|sed -e 's/"//g'|while read line
do
 namn=$(echo $line|cut -d',' -f2);url=$(echo $line|cut -d',' -f1);
 echo "insert into fmg_municipalities (mapit_name, url, mapit_id) \ 
 values ('"$namn"', '"$url"', '"$(GET "http://dev.fixamingata.se:8005/areas/${namn}"\ 
 |cut -d',' -f4|cut -d':' -f2|tr -d ' ')"'"
done > resources/populate_fmg_municipalities.sql
###insert into fmg_municipalities (mapit_name, url, mapit_id) values ('FMG-namn', 'URL', '{}');
*/
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ale', 'http://www.ale.se/', '148');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Alingsås', 'http://www.alingsas.se/', '183');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Alvesta', 'http://www.alvesta.se/', '91');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Aneby', 'http://www.aneby.se/', '289');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Arboga', 'http://www.arboga.se/', '265');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Arjeplog', 'http://www.arjeplog.se/', '83');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Arvidsjaur', 'http://www.arvidsjaur.se/', '276');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Arvika', 'http://www.arvika.se/', '114');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Askersund', 'http://www.askersund.se/', '153');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Avesta', 'http://www.avesta.se/', '28');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Bengtsfors', 'http://www.bengtsfors.se/', '135');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Berg', 'http://www.berg.se/', '250');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Bjurholm', 'http://www.bjurholm.se/', '230');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Bjuvs kommun', 'http://www.bjuv.se/', '125');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Boden', 'http://www.boden.se/', '80');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Bollebygd', 'http://www.bollebygd.se/', '196');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Bollnäs', 'http://www.bollnas.se/', '11');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Borgholm', 'http://www.borgholm.se/', '67');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Borlänge', 'http://www.borlange.se/', '23');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Borås', 'http://www.boras.se/', '181');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Botkyrka', 'http://www.botkyrka.se/', '50');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Boxholm', 'http://www.boxholm.se/', '218');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Bromölla kommun', 'http://www.bromolla.se/', '272');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Bräcke', 'http://www.bracke.se/', '109');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Burlövs kommun', 'http://www.burlov.se/', '257');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Båstads kommun', 'http://www.bastad.se/', '61');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Dals-Ed', 'http://www.dalsed.se/', '65');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Danderyd', 'http://www.danderyd.se/', '40');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Degerfors', 'http://www.degerfors.se/', '141');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Dorotea', 'http://www.dorotea.se/', '93');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Eda', 'http://www.eda.se/', '270');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ekerö', 'http://www.ekero.se/', '57');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Eksjö', 'http://www.eksjo.se/', '252');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Emmaboda', 'http://www.emmaboda.se/', '221');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Enköping', 'http://www.enkoping.se/', '26');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Eskilstuna', 'http://eskilstuna.se/', '199');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Eslövs kommun', 'http://www.eslov.se/', '201');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Essunga', 'http://www.essunga.se/', '77');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Fagersta', 'http://www.fagersta.se/', '146');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Falkenberg', 'http://www.falkenberg.se/', '72');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Falköping', 'http://www.falkoping.se/', '223');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Falun', 'http://www.falun.se/', '15');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Filipstad', 'http://www.filipstad.se/', '238');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Finspång', 'http://www.finspong.se/', '98');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Flen', 'http://www.flen.se/', '288');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Forshaga', 'http://www.forshaga.se/', '176');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Färgelanda', 'http://www.fargelanda.se/', '88');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Gagnef', 'http://www.gagnef.se/', '22');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Gislaved', 'http://www.gislaved.se/', '227');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Gnesta', 'http://www.gnesta.se/', '225');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Gnosjö', 'http://www.gnosjo.se/', '180');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Gotland', 'http://www.gotland.se/', '4');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Grums', 'http://www.grums.se/', '234');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Grästorp', 'http://www.grastorp.se/', '75');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Gullspång', 'http://www.gullspang.se/', '118');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Gällivare', 'http://www.gellivare.se/', '100');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Gävle', 'http://www.gavle.se/', '5');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Göteborgs kommun', 'http://www.goteborg.se/', '233');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Götene', 'http://www.gotene.se/', '79');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Habo', 'http://www.habokommun.se/', '66');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hagfors', 'http://www.hagfors.se/', '254');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hallsberg', 'http://www.hallsberg.se/', '202');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hallstahammar', 'http://www.hallstahammar.se/', '215');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Halmstad', 'http://www.halmstad.se/', '96');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hammarö', 'http://www.hammaro.se/', '1');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Haninge', 'http://www.haninge.se/', '49');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Haparanda', 'http://www.haparanda.se/', '209');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Heby', 'http://www.heby.se/', '18');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hedemora', 'http://www.hedemora.se/', '14');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Helsingborgs kommun', 'http://www.helsingborg.se/', '193');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Herrljunga', 'http://www.herrljunga.se/', '171');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hjo', 'http://www.hjo.se/', '280');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hofors', 'http://www.hofors.se/', '9');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Huddinge', 'http://www.huddinge.se/', '47');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hudiksvall', 'http://www.hudiksvall.se/', '262');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hultsfred', 'http://www.hultsfred.se/', '283');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hylte', 'http://www.hylte.se/', '68');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Håbo', 'http://www.habo.se/haabo', '27');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hällefors', 'http://www.hellefors.se/', '130');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Härjedalen', 'http://www.herjedalen.se/', '172');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Härnösand', 'http://www.harnosand.se/', '78');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Härryda kommun', 'http://www.harryda.se/', '263');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hässleholms kommun', 'http://www.hassleholm.se/', '158');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Höganäs kommun', 'http://www.hoganas.se/', '187');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Högsby', 'http://www.hogsby.se/', '131');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Hörby kommun', 'http://www.horby.se/', '242');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Höörs kommun', 'http://www.hoor.se/', '104');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Jokkmokk', 'http://www.jokkmokk.se/', '249');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Järfälla', 'http://www.jarfalla.se/', '38');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Jönköping', 'http://www.jonkoping.se/', '139');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kalix', 'http://www.kalix.se/', '121');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kalmar', 'http://www.kalmar.se/', '115');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Karlsborg', 'http://www.karlsborg.se/', '236');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Karlshamn', 'http://www.karlshamn.se/', '161');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Karlskoga', 'http://www.karlskoga.se/', '159');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Karlskrona', 'http://www.karlskrona.se/', '184');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Karlstad', 'http://www.karlstad.se/', '154');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Katrineholm', 'http://www.katrineholm.se/', '62');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kil', 'http://www.kil.se/', '229');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kinda', 'http://www.kinda.se/', '219');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kiruna', 'http://www.kommun.kiruna.se/', '178');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Klippans kommun', 'http://www.klippan.se/', '271');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Knivsta', 'http://www.knivsta.se/', '33');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kramfors', 'http://www.kramfors.se/', '99');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kristianstads kommun', 'http://www.kristianstad.se/', '102');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kristinehamn', 'http://www.kristinehamn.se/', '111');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Krokom', 'http://www.krokom.se/', '235');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kumla', 'http://www.kumla.se/', '138');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kungsbacka', 'http://www.kungsbacka.se/', '245');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kungsör', 'http://www.kungsor.se/', '174');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kungälv', 'http://www.kungalv.se/', '147');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Kävlinge kommun', 'http://www.kavlinge.se/', '244');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Köping', 'http://www.koping.se/', '70');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Laholm', 'http://www.laholm.se/', '273');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Landskrona kommun', 'http://www.landskrona.se/', '74');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Laxå', 'http://www.laxa.se/', '228');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lekeberg', 'http://www.lekeberg.se/', '281');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Leksand', 'http://www.leksand.se/', '21');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lerum', 'http://www.lerum.se/', '186');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lessebo', 'http://www.lessebo.se/', '160');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lidingö', 'http://www.lidingo.se/', '41');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lidköping', 'http://www.lidkoping.se/', '117');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lilla Edet', 'http://www.lillaedet.se/', '164');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lindesberg', 'http://www.lindesberg.se/', '191');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Linköping', 'http://www.linkoping.se/', '116');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ljungby', 'http://www.ljungby.se/', '179');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ljusdal', 'http://www.ljusdal.se/', '216');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ljusnarsberg', 'http://www.ljusnarsberg.se/', '194');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lomma kommun', 'http://www.lomma.se/', '71');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ludvika', 'http://www.ludvika.se/', '58');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Luleå', 'http://www.lulea.se/', '128');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lunds kommun', 'http://www.lund.se/', '275');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lycksele', 'http://www.lycksele.se/', '85');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Lysekil', 'http://www.lysekil.se/', '185');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Malmö kommun', 'http://www.malmo.se/', '76');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Malung-Sälen', 'http://www.malung.se/', '60');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Malå', 'http://www.mala.se/', '142');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mariestad', 'http://www.mariestad.se/', '81');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mark', 'http://www.mark.se/', '240');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Markaryd', 'http://www.markaryd.se/', '240');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mellerud', 'http://www.mellerud.se/', '241');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mjölby', 'http://www.mjolby.se/', '149');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mora', 'http://www.mora.se/', '17');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Motala', 'http://www.motala.se/', '277');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mullsjö', 'http://www.mullsjo.se/', '251');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Munkedal', 'http://www.munkedal.se/', '284');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Munkfors', 'http://www.munkfors.se/', '143');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mölndals kommun', 'http://www.molndal.se/', '112');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mönsterås', 'http://www.monsteras.se/', '205');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Mörbylånga', 'http://www.morbylanga.se/', '157');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nacka', 'http://www.nacka.se/', '44');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nora', 'http://www.nora.se/', '119');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Norberg', 'http://www.norberg.se/', '25');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nordanstig', 'http://www.nordanstig.se/', '259');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nordmaling', 'http://www.nordmaling.se/', '261');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Norrköping', 'http://www.norrkoping.se/', '101');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Norrtälje', 'http://www.norrtalje.se/', '34');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Norsjö', 'http://www.norsjo.se/', '217');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nybro', 'http://www.nybro.se/', '122');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nykvarn', 'http://www.nykvarn.se/', '120');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nyköping', 'http://www.nykoping.se/', '155');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nynäshamn', 'http://www.nynashamn.se/', '51');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Nässjö', 'http://www.nassjo.se/', '278');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ockelbo', 'http://www.ockelbo.se/', '6');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Olofström', 'http://www.olofstrom.se/', '226');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Orsa', 'http://www.orsa.se/', '10');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Orust', 'http://www.orust.se/', '170');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Osby kommun', 'http://www.osby.se/', '136');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Oskarshamn', 'http://www.oskarshamn.se/', '266');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ovanåker', 'http://www.ovanaker.se/', '29');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Oxelösund', 'http://www.oxelosund.se/', '162');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Pajala', 'http://www.pajala.se/', '203');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Partille kommun', 'http://www.partille.se/', '269');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Perstorps kommun', 'http://www.perstorp.se/', '168');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Piteå', 'http://www.pitea.se', '134');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ragunda', 'http://www.ragunda.se/', '192');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Robertsfors', 'http://www.robertsfors.se/', '286');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ronneby', 'http://www.ronneby.se/', '165');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Rättvik', 'http://www.rattvik.se/', '16');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sala', 'http://www.sala.se/', '31');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Salem', 'http://www.salem.se/', '55');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sandviken', 'http://www.sandviken.se/', '7');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sigtuna', 'http://www.sigtuna.se/', '32');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Simrishamns kommun', 'http://www.simrishamn.se/', '167');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sjöbo kommun', 'http://www.sjobo.se/', '163');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Skara', 'http://www.skara.se/', '150');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Skellefteå', 'http://www.skelleftea.se/', '206');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Skinnskatteberg', 'http://www.skinnskatteberg.se/', '82');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Skurups kommun', 'http://www.skurup.se/', '92');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Skövde', 'http://www.skovde.se/', '129');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Smedjebacken', 'http://www1.smedjebacken.se/', '24');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sollefteå', 'http://www.solleftea.se/', '243');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sollentuna', 'http://www.sollentuna.se/', '39');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Solna', 'http://www.solna.se/', '46');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sorsele', 'http://www.sorsele.se/', '268');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sotenäs', 'http://www.sotenas.se/', '87');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Staffanstorps kommun', 'http://www.staffanstorp.se/', '144');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Stenungsund', 'http://www.stenungsund.se/', '145');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Stockholm', 'http://www.stockholm.se/', '37');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Storfors', 'http://www.storfors.se/', '137');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Storuman', 'http://www.storuman.se/', '126');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Strängnäs', 'http://www.strangnas.se/', '54');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Strömstad', 'http://www.stromstad.se/', '133');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Strömsund', 'http://www.stromsund.se/', '73');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sundbyberg', 'http://www.sundbyberg.se/', '45');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sundsvall', 'http://www.sundsvall.se/', '140');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sunne', 'http://www.sunne.se/', '246');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Surahammar', 'http://www.surahammar.se/', '84');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Svalövs kommun', 'http://www.svalov.se/', '64');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Svedala kommun', 'http://www.svedala.se/', '151');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Svenljunga', 'http://www.svenljunga.se/', '213');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Säffle', 'http://www.saffle.se/', '220');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Säter', 'http://www.sater.se/', '13');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sävsjö', 'http://www.savsjo.se/', '127');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Söderhamn', 'http://www.soderhamn.se/', '12');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Söderköping', 'http://www.soderkoping.se/', '190');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Södertälje', 'http://www.sodertalje.se/', '56');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Sölvesborg', 'http://www.solvesborg.se/', '231');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tanum', 'http://www.tanum.se/', '256');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tibro', 'http://www.tibro.se/', '264');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tidaholm', 'http://www.tidaholm.se/', '197');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tierp', 'http://www.tierp.se/', '19');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Timrå', 'http://www.timra.se/', '198');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tingsryd', 'http://www.tingsryd.se/', '208');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tjörn', 'http://www.tjorn.se/', '3');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tomelilla kommun', 'http://www.tomelilla.se/', '279');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Torsby', 'http://www.torsby.se/', '287');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Torsås', 'http://www.torsas.se/', '152');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tranemo', 'http://www.tranemo.se/', '211');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tranås', 'http://www.tranas.se/', '200');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Trelleborgs kommun', 'http://www.trelleborg.se/', '169');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Trollhättan', 'http://www.trollhattan.se/', '232');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Trosa', 'http://www.trosa.se/', '110');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Tyresö', 'http://www.tyreso.se/', '48');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Täby', 'http://www.taby.se/', '36');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Töreboda', 'http://www.toreboda.se/', '253');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Uddevalla', 'http://www.uddevalla.se/', '258');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ulricehamn', 'http://www.ulricehamn.se/', '189');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Umeå', 'http://www.umea.se/', '260');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Upplands Väsby', 'http://www.upplandsvasby.se/', '35');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Upplands-Bro', 'http://www.upplands-bro.se/', '30');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Uppsala', 'http://www.uppsala.se/', '20');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Uppvidinge', 'http://www.uppvidinge.se/', '132');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vadstena', 'http://www.vadstena.se/', '188');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vaggeryd', 'http://www.vaggeryd.se/', '210');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Valdemarsvik', 'http://www.valdemarsvik.se/', '97');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vallentuna', 'http://www.vallentuna.se/', '290');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vansbro', 'http://www.vansbro.se/', '59');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vara', 'http://www.vara.se/', '123');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Varberg', 'http://www.varberg.se/', '212');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vaxholm', 'http://www.vaxholm.se/', '42');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vellinge kommun', 'http://www.vellinge.se/', '105');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vetlanda', 'http://www.vetlanda.se/', '107');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vilhelmina', 'http://www.vilhelmina.se/', '166');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vimmerby', 'http://www.vimmerby.se/', '182');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vindeln', 'http://www.vindeln.se/', '63');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vingåker', 'http://www.vingaker.se/', '282');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vårgårda', 'http://www.vargarda.se', '95');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vänersborg', 'http://www.vanersborg.se/', '106');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Vännäs', 'http://www.vannas.se/', '195');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Värmdö', 'http://www.varmdo.se/', '52');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Värnamo', 'http://www.varnamo.se/', '94');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Västervik', 'http://www.vastervik.se/', '69');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Västerås', 'http://www.vasteras.se/', '214');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Växjö', 'http://www.vaxjo.se/', '267');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ydre', 'http://www.ydre.se/', '237');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ystads kommun', 'http://www.ystad.se/', '222');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Åmål', 'http://www.amal.se/', '224');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ånge', 'http://www.ange.se/', '124');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Åre', 'http://www.are.se/', '86');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Årjäng', 'http://www.arjang.se/', '274');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Åsele', 'http://www.asele.se/', '89');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Åstorps kommun', 'http://www.astorp.se/', '156');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Åtvidaberg', 'http://www.atvidaberg.se/', '113');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Älmhult', 'http://www.almhult.se/', '175');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Älvdalen', 'http://www.alvdalen.se/', '177');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Älvkarleby', 'http://www.alvkarleby.se/', '8');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Älvsbyn', 'http://www.alvsbyn.se/', '204');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ängelholms kommun', 'www.engelholm.se', '285');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Öckerö', 'http://www.ockero.se/', '2');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Ödeshög', 'http://www.odeshog.se/', '90');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Örebro', 'http://www.orebro.se/', '247');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Örkelljunga kommun', 'http://www.orkelljunga.se/', '103');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Örnsköldsvik', 'http://www.ornskoldsvik.se/', '108');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Östersund', 'http://www.ostersund.se/', '207');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Österåker', 'http://www.osteraker.se/', '43');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Östhammar', 'http://www.osthammar.se/', '53');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Östra Göinge kommun', 'http://www.ostragoinge.se/', '173');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Överkalix', 'http://www.overkalix.se/', '248');
insert into fmg_municipalities (mapit_name, url, mapit_id) values ('Övertorneå', 'http://www.overtornea.se/', '239');
